In [3]:
 pip install numpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (1.24.3)




[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [10]:
a=np.array(13)
print(a)
print(type(a))
print(a.ndim)

13
<class 'numpy.ndarray'>
0


In [11]:
b=np.array([1,2,3,4])
print(b)
print(b.ndim)

[1 2 3 4]
1


In [12]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [13]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d)
print(d.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3
